### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by DavidLRowe** [silnrsi/silfontdev#1]
Going to https://github.com/silnrsi/silfontdev displays the README.md file, 
which has a link to https://github.com/silnrsi/silfontdev/en-US-weightlist.md 
which returns "Not Found".
It seems like it might need to change to:
https://github.com/silnrsi/silfontdev/blob/master/en-US-weightlist.md

**Comment by n7s** [comment]
Good catch. Fixed in bf7a3b1.
